### PR TITLE
Fix README

### PR DESCRIPTION
**Pull request by sayanchowdhury**

### CODE REVIEW

**Comment by LalatenduMohanty** [comment]
@sayanchowdhury LGTM except the commit message should say " Fxing Django/README.md" or something more specific about which readme.

**Comment by sayanchowdhury** [comment]
@LalatenduMohanty Yes, make sense. updated the commit message to "Fixing Django/README.md"

**Comment by LalatenduMohanty** [comment]
LGTM

**Comment by scollier** [comment]
Thanks for the review @LalatenduMohanty 

Thanks for the fix @sayanchowdhury

**Pull request merged**
