### PR TITLE
bind: Simplified to single app (removed supervisord, sshd etc)

### PR DESCRIPTION
**Pull request by docent-net**
Removed supervisord and rest of the apps (ssh, rsyslog, logrotate) and left single-app container.

### CODE REVIEW

**Comment by scollier** [comment]
terribly sorry for the delay @docent-net .  I've been traveling and will be traveling next week.  However, I'll try to give this a review then.

**Comment by bkabrda** [comment]
Builds and runs fine, nice job!

Two small nitpicks:
- README doesn't contain Docker version that this Dockerfile was created and tested on - the Guidelines [1] require this.
- The "Testing" section recommends using `docker inspect -format`, but `-format` is deprecated (since 1.8.0) and `--format` should be used now.

[1] https://github.com/fedora-cloud/Fedora-Dockerfiles/wiki/Guidelines-for-Creating-Dockerfiles

**Comment by docent-net** [comment]
@bkabrda: fixed - thanks

Also replaced yum with dnf

**Comment by bkabrda** [comment]
Thanks, merging!

**Pull request merged**
