### PR TITLE
Ruby Dockerfile

### PR DESCRIPTION
**Pull request by sarupbanskota**
I'm new to Docker, had some issues setting things up, but I'd like to add this dockerfile as a starting point. Any suggestions on what I need to add/remove/improve?

### CODE REVIEW

**Comment by scollier** [comment]
Hi @sarupbanskota , please include a README with a simple example, please check in the other directories for example READMEs.

**Comment by scollier** [comment]
@sarupbanskota just checking in here.

**Comment by scollier** [comment]
@sarupbanskota Checking in.

**Comment by sarupbanskota** [comment]
Oh no! So sorry I completely missed this. I'll get this updated by the
weekend :) thanks!

**Comment by scollier** [comment]
LGTM.  Sorry for the delay and thank you for the contribution.

**Pull request merged**
