### PR TITLE
Adding required file to package in Jenkins in Fedora conatiner.

### PR DESCRIPTION
**Pull request by LalatenduMohanty**
This patch uses supervisord to run Jenkins process.

Signed-off-by: Lalatendu Mohanty <lmohanty@redhat.com>

### CODE REVIEW

**Comment by scollier** [comment]
Thanks.  Please combine the package  install lines in the Dockerfile and remove the reference  to httpd in the readme.  Other than that, LGTM.

**Comment by LalatenduMohanty** [comment]
Thanks for the review Scott. I have updated the pull request.

**Comment by scollier** [comment]
LGTM.

**Comment by scollier** [comment]
LGTM.

**Comment by scollier** [comment]
LGTM.

**Comment by scollier** [comment]
LGTM.

**Pull request merged**
