### PR TITLE
CUPS: Add printer based on environment variables

### PR DESCRIPTION
**Pull request by ngrash**
Motivated by my recently merged pull request I dare to request another one.

This one adds a printer based on the environment variables CUPS_PRINTER_NAME, CUPS_PRINTER_DRIVER, and CUPS_PRINTER_CONNECTION.

Use case: You want to quickly set up a known printer in an automated environment without the need to log into the web interface (which would certainly break automation).

I am not sure if this kind of change fits the philosophy of the project, but if so I would happily extend the README. Please let me know what you think.

### CODE REVIEW

**Comment by scollier** [comment]
Hey @ngrash, Sorry for the delay.  I've built the image and I'm testing it now.  Just wanted to give you status.

**Comment by scollier** [comment]
@ngrash Got it.  Thanks.  We can't assume that others will be using fig.  Can you please give the -e a try, and if it works, update the README?  I think then we'd be good to go once functionality is confirmed.

**Comment by ngrash** [comment]
@scollier `docker -e` is working as expected and I updated the README to explain the new variables.

**Comment by scollier** [comment]
LGTM. Thanks @ngrash

**Pull request merged**
