### PR TITLE
Improve docker example for nodejs

### PR DESCRIPTION
**Pull request by vodolaz095**
- Update nodejs Dockerfile to use `dnf` instead of `yum`. 
- Add caching of npm modules installed.
- Some small improvements on nodejs application example.

### CODE REVIEW

**Comment by vodolaz095** [comment]
in my opinion it works as intended - builds nodejs application that listens on 8080 port of container

```shell

[root@steel nodejs]# docker build .
Sending build context to Docker daemon 27.14 kB
Step 1 : FROM fedora:23
 ---> 0721f2b3cb16
Step 2 : MAINTAINER http://fedoraproject.org/wiki/Cloud
 ---> Using cache
 ---> db17694b7002
Step 3 : RUN dnf -y update
 ---> Using cache
 ---> c97818ecd853
Step 4 : RUN dnf -y install npm
 ---> Using cache
 ---> 8ec6ff3a3299
Step 5 : RUN dnf clean all
 ---> Using cache
 ---> d5a276a15a8e
Step 6 : RUN node -v
 ---> Running in fbc966a44547
v0.10.36
 ---> fc2a8949cbb0
Removing intermediate container fbc966a44547
Step 7 : RUN npm -v
 ---> Running in 738e5c6485a5
1.3.6
 ---> 8382168f2e06
Removing intermediate container 738e5c6485a5
Step 8 : ENV PORT 8080
 ---> Running in 98653034936f
 ---> 577b6abc6e0a
Removing intermediate container 98653034936f
Step 9 : EXPOSE 8080
 ---> Running in d61bfebe35e7
 ---> d1256beb1b53
Removing intermediate container d61bfebe35e7
Step 10 : ENV NODE_ENV production
 ---> Running in 9d2ea7dff7af
 ---> 3f99b9ed5c25
Removing intermediate container 9d2ea7dff7af
Step 11 : RUN mkdir /src
 ---> Running in f5b316c24f92
 ---> 3d4bb729547c
Removing intermediate container f5b316c24f92
Step 12 : ADD package.json /src
 ---> 0bc46467d337
Removing intermediate container 1b792edc7958
Step 13 : RUN cd /src; npm install
 ---> Running in 52981e29e139
npm http GET https://registry.npmjs.org/express
npm http 200 https://registry.npmjs.org/express
npm http GET https://registry.npmjs.org/express/-/express-4.13.4.tgz
npm http 200 https://registry.npmjs.org/express/-/express-4.13.4.tgz
npm http GET https://registry.npmjs.org/accepts
npm http GET https://registry.npmjs.org/content-disposition/0.5.1
npm http GET https://registry.npmjs.org/array-flatten/1.1.1
npm http GET https://registry.npmjs.org/content-type
npm http GET https://registry.npmjs.org/cookie/0.1.5
npm http GET https://registry.npmjs.org/cookie-signature/1.0.6
npm http GET https://registry.npmjs.org/debug
npm http GET https://registry.npmjs.org/depd
npm http GET https://registry.npmjs.org/escape-html
npm http GET https://registry.npmjs.org/etag
npm http GET https://registry.npmjs.org/merge-descriptors/1.0.1
npm http GET https://registry.npmjs.org/methods
npm http GET https://registry.npmjs.org/on-finished
npm http GET https://registry.npmjs.org/parseurl
npm http GET https://registry.npmjs.org/path-to-regexp/0.1.7
npm http GET https://registry.npmjs.org/proxy-addr
npm http GET https://registry.npmjs.org/range-parser
npm http GET https://registry.npmjs.org/send/0.13.1
npm http GET https://registry.npmjs.org/serve-static
npm http GET https://registry.npmjs.org/qs/4.0.0
npm http GET https://registry.npmjs.org/type-is
npm http GET https://registry.npmjs.org/utils-merge/1.0.0
npm http GET https://registry.npmjs.org/vary
npm http GET https://registry.npmjs.org/finalhandler/0.4.1
npm http GET https://registry.npmjs.org/fresh/0.3.0
npm http 200 https://registry.npmjs.org/content-type
npm http GET https://registry.npmjs.org/content-type/-/content-type-1.0.1.tgz
npm http 200 https://registry.npmjs.org/accepts
npm http GET https://registry.npmjs.org/accepts/-/accepts-1.2.13.tgz
npm http 200 https://registry.npmjs.org/debug
npm http GET https://registry.npmjs.org/debug/-/debug-2.2.0.tgz
npm http 200 https://registry.npmjs.org/content-type/-/content-type-1.0.1.tgz
npm http 200 https://registry.npmjs.org/accepts/-/accepts-1.2.13.tgz
npm http 200 https://registry.npmjs.org/content-disposition/0.5.1
npm http GET https://registry.npmjs.org/content-disposition/-/content-disposition-0.5.1.tgz
npm http 200 https://registry.npmjs.org/debug/-/debug-2.2.0.tgz
npm http 200 https://registry.npmjs.org/escape-html
npm http GET https://registry.npmjs.org/escape-html/-/escape-html-1.0.3.tgz
npm http 200 https://registry.npmjs.org/content-disposition/-/content-disposition-0.5.1.tgz
npm http 200 https://registry.npmjs.org/cookie/0.1.5
npm http GET https://registry.npmjs.org/cookie/-/cookie-0.1.5.tgz
npm http 200 https://registry.npmjs.org/array-flatten/1.1.1
npm http GET https://registry.npmjs.org/array-flatten/-/array-flatten-1.1.1.tgz
npm http 200 https://registry.npmjs.org/escape-html/-/escape-html-1.0.3.tgz
npm http 200 https://registry.npmjs.org/methods
npm http 200 https://registry.npmjs.org/cookie-signature/1.0.6
npm http GET https://registry.npmjs.org/methods/-/methods-1.1.2.tgz
npm http GET https://registry.npmjs.org/cookie-signature/-/cookie-signature-1.0.6.tgz
npm http 200 https://registry.npmjs.org/on-finished
npm http GET https://registry.npmjs.org/on-finished/-/on-finished-2.3.0.tgz
npm http 200 https://registry.npmjs.org/merge-descriptors/1.0.1
npm http GET https://registry.npmjs.org/merge-descriptors/-/merge-descriptors-1.0.1.tgz
npm http 200 https://registry.npmjs.org/parseurl
npm http GET https://registry.npmjs.org/parseurl/-/parseurl-1.3.1.tgz
npm http 200 https://registry.npmjs.org/cookie/-/cookie-0.1.5.tgz
npm http 200 https://registry.npmjs.org/array-flatten/-/array-flatten-1.1.1.tgz
npm http 200 https://registry.npmjs.org/depd
npm http 200 https://registry.npmjs.org/proxy-addr
npm http 200 https://registry.npmjs.org/merge-descriptors/-/merge-descriptors-1.0.1.tgz
npm http 200 https://registry.npmjs.org/path-to-regexp/0.1.7
npm http GET https://registry.npmjs.org/depd/-/depd-1.1.0.tgz
npm http GET https://registry.npmjs.org/proxy-addr/-/proxy-addr-1.0.10.tgz
npm http 200 https://registry.npmjs.org/parseurl/-/parseurl-1.3.1.tgz
npm http 200 https://registry.npmjs.org/cookie-signature/-/cookie-signature-1.0.6.tgz
npm http 200 https://registry.npmjs.org/send/0.13.1
npm http GET https://registry.npmjs.org/path-to-regexp/-/path-to-regexp-0.1.7.tgz
npm http 200 https://registry.npmjs.org/methods/-/methods-1.1.2.tgz
npm http 200 https://registry.npmjs.org/proxy-addr/-/proxy-addr-1.0.10.tgz
npm http GET https://registry.npmjs.org/send/-/send-0.13.1.tgz
npm http 200 https://registry.npmjs.org/on-finished/-/on-finished-2.3.0.tgz
npm http 200 https://registry.npmjs.org/range-parser
npm http 200 https://registry.npmjs.org/serve-static
npm http 200 https://registry.npmjs.org/type-is
npm http GET https://registry.npmjs.org/range-parser/-/range-parser-1.0.3.tgz
npm http GET https://registry.npmjs.org/serve-static/-/serve-static-1.10.2.tgz
npm http GET https://registry.npmjs.org/type-is/-/type-is-1.6.10.tgz
npm http 200 https://registry.npmjs.org/utils-merge/1.0.0
npm http 200 https://registry.npmjs.org/vary
npm http 200 https://registry.npmjs.org/qs/4.0.0
npm http 200 https://registry.npmjs.org/finalhandler/0.4.1
npm http GET https://registry.npmjs.org/utils-merge/-/utils-merge-1.0.0.tgz
npm http 200 https://registry.npmjs.org/etag
npm http 200 https://registry.npmjs.org/depd/-/depd-1.1.0.tgz
npm http 200 https://registry.npmjs.org/fresh/0.3.0
npm http GET https://registry.npmjs.org/vary/-/vary-1.0.1.tgz
npm http GET https://registry.npmjs.org/qs/-/qs-4.0.0.tgz
npm http GET https://registry.npmjs.org/finalhandler/-/finalhandler-0.4.1.tgz
npm http 200 https://registry.npmjs.org/path-to-regexp/-/path-to-regexp-0.1.7.tgz
npm http GET https://registry.npmjs.org/etag/-/etag-1.7.0.tgz
npm http GET https://registry.npmjs.org/fresh/-/fresh-0.3.0.tgz
npm http 200 https://registry.npmjs.org/type-is/-/type-is-1.6.10.tgz
npm http 200 https://registry.npmjs.org/send/-/send-0.13.1.tgz
npm http 200 https://registry.npmjs.org/utils-merge/-/utils-merge-1.0.0.tgz
npm http 200 https://registry.npmjs.org/vary/-/vary-1.0.1.tgz
npm http 200 https://registry.npmjs.org/qs/-/qs-4.0.0.tgz
npm http 200 https://registry.npmjs.org/finalhandler/-/finalhandler-0.4.1.tgz
npm http 200 https://registry.npmjs.org/range-parser/-/range-parser-1.0.3.tgz
npm http 200 https://registry.npmjs.org/serve-static/-/serve-static-1.10.2.tgz
npm http 200 https://registry.npmjs.org/etag/-/etag-1.7.0.tgz
npm http 200 https://registry.npmjs.org/fresh/-/fresh-0.3.0.tgz
npm http GET https://registry.npmjs.org/unpipe
npm http GET https://registry.npmjs.org/ee-first/1.1.1
npm http GET https://registry.npmjs.org/forwarded
npm http GET https://registry.npmjs.org/ipaddr.js/1.0.5
npm http GET https://registry.npmjs.org/media-typer/0.3.0
npm http GET https://registry.npmjs.org/mime-types
npm http GET https://registry.npmjs.org/mime-types
npm http GET https://registry.npmjs.org/negotiator/0.5.3
npm http GET https://registry.npmjs.org/destroy
npm http GET https://registry.npmjs.org/http-errors
npm http GET https://registry.npmjs.org/mime/1.3.4
npm http GET https://registry.npmjs.org/ms/0.7.1
npm http GET https://registry.npmjs.org/statuses
npm http 200 https://registry.npmjs.org/unpipe
npm http 200 https://registry.npmjs.org/ee-first/1.1.1
npm http GET https://registry.npmjs.org/unpipe/-/unpipe-1.0.0.tgz
npm http GET https://registry.npmjs.org/ee-first/-/ee-first-1.1.1.tgz
npm http 200 https://registry.npmjs.org/forwarded
npm http 200 https://registry.npmjs.org/media-typer/0.3.0
npm http GET https://registry.npmjs.org/forwarded/-/forwarded-0.1.0.tgz
npm http GET https://registry.npmjs.org/media-typer/-/media-typer-0.3.0.tgz
npm http 200 https://registry.npmjs.org/negotiator/0.5.3
npm http GET https://registry.npmjs.org/negotiator/-/negotiator-0.5.3.tgz
npm http 200 https://registry.npmjs.org/destroy
npm http GET https://registry.npmjs.org/destroy/-/destroy-1.0.4.tgz
npm http 200 https://registry.npmjs.org/ipaddr.js/1.0.5
npm http GET https://registry.npmjs.org/ipaddr.js/-/ipaddr.js-1.0.5.tgz
npm http 200 https://registry.npmjs.org/mime/1.3.4
npm http GET https://registry.npmjs.org/mime/-/mime-1.3.4.tgz
npm http 200 https://registry.npmjs.org/mime-types
npm http 200 https://registry.npmjs.org/mime-types
npm http 200 https://registry.npmjs.org/http-errors
npm http GET https://registry.npmjs.org/mime-types/-/mime-types-2.1.9.tgz
npm http GET https://registry.npmjs.org/http-errors/-/http-errors-1.3.1.tgz
npm http 200 https://registry.npmjs.org/unpipe/-/unpipe-1.0.0.tgz
npm http 200 https://registry.npmjs.org/ee-first/-/ee-first-1.1.1.tgz
npm http 200 https://registry.npmjs.org/statuses
npm http 200 https://registry.npmjs.org/forwarded/-/forwarded-0.1.0.tgz
npm http 200 https://registry.npmjs.org/media-typer/-/media-typer-0.3.0.tgz
npm http GET https://registry.npmjs.org/statuses/-/statuses-1.2.1.tgz
npm http 200 https://registry.npmjs.org/destroy/-/destroy-1.0.4.tgz
npm http 200 https://registry.npmjs.org/ipaddr.js/-/ipaddr.js-1.0.5.tgz
npm http 200 https://registry.npmjs.org/negotiator/-/negotiator-0.5.3.tgz
npm http 200 https://registry.npmjs.org/mime-types/-/mime-types-2.1.9.tgz
npm http 200 https://registry.npmjs.org/mime/-/mime-1.3.4.tgz
npm http 200 https://registry.npmjs.org/http-errors/-/http-errors-1.3.1.tgz
npm http 200 https://registry.npmjs.org/ms/0.7.1
npm http 200 https://registry.npmjs.org/statuses/-/statuses-1.2.1.tgz
npm http GET https://registry.npmjs.org/ms/-/ms-0.7.1.tgz
npm http 200 https://registry.npmjs.org/ms/-/ms-0.7.1.tgz
npm http GET https://registry.npmjs.org/mime-db
npm http GET https://registry.npmjs.org/inherits
npm http 200 https://registry.npmjs.org/mime-db
npm http GET https://registry.npmjs.org/mime-db/-/mime-db-1.21.0.tgz
npm http 200 https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/inherits/-/inherits-2.0.1.tgz
npm http 200 https://registry.npmjs.org/inherits/-/inherits-2.0.1.tgz
npm http 200 https://registry.npmjs.org/mime-db/-/mime-db-1.21.0.tgz
express@4.13.4 node_modules/express
├── escape-html@1.0.3
├── array-flatten@1.1.1
├── cookie-signature@1.0.6
├── path-to-regexp@0.1.7
├── merge-descriptors@1.0.1
├── utils-merge@1.0.0
├── methods@1.1.2
├── fresh@0.3.0
├── range-parser@1.0.3
├── vary@1.0.1
├── cookie@0.1.5
├── parseurl@1.3.1
├── content-type@1.0.1
├── etag@1.7.0
├── content-disposition@0.5.1
├── serve-static@1.10.2
├── depd@1.1.0
├── qs@4.0.0
├── finalhandler@0.4.1 (unpipe@1.0.0)
├── on-finished@2.3.0 (ee-first@1.1.1)
├── debug@2.2.0 (ms@0.7.1)
├── proxy-addr@1.0.10 (forwarded@0.1.0, ipaddr.js@1.0.5)
├── send@0.13.1 (destroy@1.0.4, ms@0.7.1, statuses@1.2.1, mime@1.3.4, http-errors@1.3.1)
├── type-is@1.6.10 (media-typer@0.3.0, mime-types@2.1.9)
└── accepts@1.2.13 (negotiator@0.5.3, mime-types@2.1.9)
 ---> 541557b3e35d
Removing intermediate container 52981e29e139
Step 14 : ADD . /src
 ---> a48434cb6927
Removing intermediate container ff3fe51fce2b
Step 15 : CMD node /src/index.js
 ---> Running in de035cd58d00
 ---> 0e3ba8b8a769
Removing intermediate container de035cd58d00
Successfully built 0e3ba8b8a769

[root@steel nodejs]# docker run -d -p 8080:8080 0e3ba8

[root@steel nodejs]#  curl http://localhost:8080
Hello from Docker container!

```

**Comment by adelton** [comment]
I agree with the replacement of `yum` with `dnf`. But splitting into multiple `RUN`s will prevent the `dnf clean` from doing its job.

Also, in the master branch we might want to keep the `FROM fedora` without version -- that will always get the `latest`. Any Fedora 23 specific things should likely live in the f23 branch.

I cannot comment on the node/npm parts of the proposed patch.

**Comment by vodolaz095** [comment]
for `But splitting into multiple RUNs will prevent the dnf clean from doing its job.`
 i have explained my point of view here
https://github.com/fedora-cloud/Fedora-Dockerfiles/pull/177#issuecomment-179854365

**Comment by vodolaz095** [comment]
@adelton  i have fixed the multiple `dnf` calls

**Comment by adelton** [comment]
> i have fixed the multiple dnf calls

LGTM.

**Comment by scollier** [comment]
Thanks for review @adelton 

Thanks for PR @vodolaz095

**Pull request merged**
