### PR TITLE
Added p7zip and ordered the package list

### PR DESCRIPTION
**Pull request by e-minguez**

### CODE REVIEW

**Comment by bkabrda** [comment]
Hi, would you please explain why adding the package is a good idea? Also, we're still working on organizing PRs to this repo, but for now the policy is that PRs should be submitted to f22 branch (sorry it's not mentioned anywhere...).

So please resubmit this PR against f22 with an explanation why this package should be added.

**Comment by scollier** [comment]
Hi @e-minguez, checking in here.  Can you please follow up on @bkabrda's request for explanation?  Thanks.  Also, when @bkabrda made the statement on submitting against the f22 branch, it was correct.  However, as of a week ago, the decision was made to go back to master.  So, submitting against master is fine, but explanation is needed.  Thanks.

**Comment by e-minguez** [comment]
Having p7zip can be useful for uncompress 7z files and it is <2 mb. Speaking about the order, I think it would be nice to have the package list ordered (it is considered a good practices AFAIK)

**Comment by scollier** [comment]
@bkabrda any concerns with bringing this in?

**Comment by scollier** [comment]
@dustymabe @adelton y'all have any thoughts on this?  At what point to we provide a default set of packages for the tools container, and then instruct the user to use that as a base and start adding to it and building their own layers on top of it?

**Comment by adelton** [comment]
I'd like to see the change split into two commits -- ordering and adding new package are different things.

There seems to be `ltrace` there twice (already in existing list), might be worth cleaning it up.

I have my reservations about adding `p7zip`. I have never used it (did not come across something that was packages with it) but obviourlsy I'm only a lone statistics point. Is there some data about popuparity of various compressing formats? I agree that it seems quite feasible to build another image with `p7zip` on top of existing `tools`.

**Comment by dustymabe** [comment]
+1 to splitting up commits. 

@scollier what branch should this PR be submitted against?

**Comment by scollier** [comment]
I agree with the splitting as @adelton  mentioned.  

@dustymabe master.  Since Fedora 21 is EOL now, we can carry on with dnf everywhere.  This was decided in one of the Cloud working group meetings.   In addition, @adelton has done a great job of cleaning up master in prep for this.

@adelton I hear ya on the points of reference.  I am ambivalent here.  I don't want to push back to much, it's the first request for extension.  If we get many more, I'll bring it up to the cloud-wg.

@e-minguez  mind rebasing, splitting this up and submitting against master?

**Comment by scollier** [comment]
ping @e-minguez

**Comment by scollier** [comment]
ping @e-minguez checking in.

**Comment by scollier** [comment]
Hi @e-minguez Checking in.

**Comment by e-minguez** [comment]
Re-done in https://github.com/fedora-cloud/Fedora-Dockerfiles/pull/189

**Pull request closed without merging**
