### PR TITLE
Migrate Lighttpd service to systemd

### PR DESCRIPTION
**Pull request by praveenkumar**
https://fedorahosted.org/cloud/ticket/121 -> Initiative to migrate dockerfile to systemd when it possible.
(Reopen PR against master as suggested by @scollier )

### CODE REVIEW

**Comment by scollier** [comment]
@praveenkumar, thanks for resubmitting.  Looks like it needs to be rebased.  Can you please do that and remove the extra commits here?

**Comment by scollier** [comment]
Hi @praveenkumar, just checking in here.

**Comment by praveenkumar** [comment]
@scollier Done rebase.

**Comment by scollier** [comment]
Excellent @praveenkumar LGTM.  Thank you for working with me on this.

**Pull request merged**
