### PR TITLE
Add authentication to squid

### PR DESCRIPTION
**Pull request by danvarga**
Makes adding auth to squid simple.

### CODE REVIEW

**Comment by scollier** [comment]
Hey @danvarga, I tried setting this up and it's not prompting me.  In the Dockerfile, I changed the line to auth_squid.conf:

# Change squid.conf to auth_squid.conf if you
# would like to use authentication
ADD ./auth_squid.conf /etc/squid/auth_squid.conf

Then, I ran built and ran the container, and it's listing on 3128.  So, I go to my chrome browser and set network proxy to be on "manual, and 127.0.0.1:3128".  

I then exec into the container and look at log files:

$ docker exec -it 285 /bin/bash; tail -f /var/log/squid/*

And I can see traffic when I go to any website in the chrome browser.  However, it's not prompting me to authenticate. 

What am  I missing here?

**Comment by danvarga** [comment]
Hey @scollier, sorry I should have been more clear.  It should read:
ADD ./auth_squid.conf /etc/squid/squid.conf
not:
ADD ./auth_squid.conf /etc/squid/auth_squid.conf

I will adjust the directions

**Comment by danvarga** [comment]
Updated.

**Comment by scollier** [comment]
@danvarga please rebase

**Comment by danvarga** [comment]
squashed

**Comment by scollier** [comment]
Thanks @danvarga.  I had to make a slight change in order to be prompted for the uname / password that was created.  Check out:

$ diff auth_squid.conf.works auth_squid.conf.orig 
30d29
< auth_param basic realm proxy
33d31
< acl authenticated proxy_auth REQUIRED
45,46c43
< # http_access allow localhost manager
< http_access allow authenticated
---
> http_access allow localhost manager

Other than that, LGTM.

**Pull request merged**
