### PR TITLE
Use 'cont-postgresql' project for 'postgresql' component

### PR DESCRIPTION
**Pull request by praiskup**
The intention will be to keep the future Fedora/CentOS/RHEL (PostgreSQL)
images in sync.  Commits from this pullrequest would be the first step to
making that effort as painless as possible.

### CODE REVIEW

**Comment by praiskup** [comment]
@hhorak, @mnagy cc fyi

**Comment by scollier** [comment]
@dustymabe cc here, a PR review would be helpful.

**Comment by dustymabe** [comment]
@scollier - will try to get to this and the X2GO dockerfiles today.

**Comment by tjanez** [comment]
Hi!

I've just tried this today since I wanted to build a PostgreSQL 9.4 Docker Image from Fedora 22 Beta Base Docker Image.

Steps:
- `wget http://download.fedoraproject.org/pub/fedora/linux/releases/test/22_Beta/Docker/x86_64/Fedora-Docker-Base-22_Beta-20150415.x86_64.tar.xz`
- `docker load -i Fedora-Docker-Base-22_Beta-20150415.x86_64.tar.xz`
- edit `Dockerfile` and change `FROM` to: `Fedora-Docker-Base-22_Beta-20150415.x86_64`
- `docker build --rm -t fedora/postgresql . |& tee postgres_build.log`

The build completes successfully (except for the warning to use `dnf` instead of `yum`).

However, running a container fails:
```bash
(~/docker/Fedora-Dockerfiles/postgresql) internal $ docker run -d --name postgresql -e POSTGRESQL_CONTAINER_OPTS="assert_external_data = false" fedora/postgresql
e7251aa75281e1c41c89d4305c25d8b13633bbffbf335e3e5528a57a85d47706
(~/docker/Fedora-Dockerfiles/postgresql) internal $ docker logs postgresql
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/pgsql/data ... ok
creating subdirectories ... ok
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting dynamic shared memory implementation ... posix
creating configuration files ... ok
creating template1 database in /var/lib/pgsql/data/base/1 ... ok
initializing pg_authid ... ok
initializing dependencies ... ok
creating system views ... ok
loading system objects' descriptions ... ok
creating collations ... ok
creating conversions ... ok
creating dictionaries ... ok
setting privileges on built-in objects ... ok
creating information schema ... ok
loading PL/pgSQL server-side language ... ok
vacuuming database template1 ... ok
copying template1 to template0 ... ok
copying template1 to postgres ... ok

WARNING: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.
syncing data to disk ... ok

Success. You can now start the database server using:

    postgres -D /var/lib/pgsql/data
or
    pg_ctl -D /var/lib/pgsql/data -l logfile start

/usr/libexec/cont-postgresql-preexec: line 44: /usr/bin/postgresql-check-db-dir: No such file or directory
(~/docker/Fedora-Dockerfiles/postgresql) internal $
```

I believe the problem is that PostgreSQL 9.4 doesn't ship with `postgresql-check-db-dir` binary anymore.

If the repository targets Fedora 21, then this shouldn't be a blocker, but just a heads-up for the upcoming Fedora 22 release.

**Comment by praiskup** [comment]
@tjanez Thanks a lot for testing!  Yes, for f22+  /usr/libexec/postgresql-check-db-dir needs to
be used.

**Comment by praiskup** [comment]
Ping, can I help with the review somehow?

**Comment by hhorak** [comment]
Looked, seen no issues and the container works fine! +1 from myself!! Thanks Pavle!

**Comment by scollier** [comment]
after a quick smoke test, I tried it with FROM fedora:21 and got:

```
$ docker logs 7471a1e5e85f
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

initdb: could not change permissions of directory "/var/lib/pgsql/data": Operation not permitted
fixing permissions on existing directory /var/lib/pgsql/data ... 
```

I just copied and pasted commands from the README.  I am on a Fedora 21 host doing this testing.  I did change the FROM on the Dockerfile to: FROM fedora:21

**Comment by praiskup** [comment]
@scollier, thanks for the test.  Not reproducible on my f21.x86_64 box, however
```
...
Successfully built e0432e0cd7a2
$ mkdir data
$ sudo chown postgres:postgres data
$ sudo chcon system_u:object_r:svirt_sandbox_file_t:s0 data
$ docker run -d -v "`pwd`/data:/var/lib/pgsql/data" -p 5432:5432 e0432e0cd7a2
03323b3a0b2bb656b29c34cff406c67fbdae87388ab126cc6445fce419fbec48
$ docker logs 03323b3
The files belonging to this database system will be owned by user "postgres".
This user must also own the server process.

The database cluster will be initialized with locale "en_US.utf8".
The default database encoding has accordingly been set to "UTF8".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/pgsql/data ... ok
creating subdirectories ... ok
selecting default max_connections ... 100
selecting default shared_buffers ... 128MB
selecting dynamic shared memory implementation ... posix
creating configuration files ... ok
creating template1 database in /var/lib/pgsql/data/base/1 ... ok
initializing pg_authid ... ok
initializing dependencies ... ok
creating system views ... ok
loading system objects' descriptions ... ok
creating collations ... ok
creating conversions ... ok
creating dictionaries ... ok
setting privileges on built-in objects ... ok
creating information schema ... ok
loading PL/pgSQL server-side language ... ok
vacuuming database template1 ... ok
copying template1 to template0 ... ok
copying template1 to postgres ... ok
syncing data to disk ... ok

WARNING: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.

Success. You can now start the database server using:

    postgres -D /var/lib/pgsql/data
or
    pg_ctl -D /var/lib/pgsql/data -l logfile start

LOG:  redirecting log output to logging collector process
HINT:  Future log output will appear in directory "pg_log"
```

Probably the permission could be the issue?  I'll update the README.md in a
minute.  If that does not help, could you please try to check what are the
permissions of /var/lib/pgsql/data within container?

**Comment by scollier** [comment]
@praiskup sure.  I have time to look at it this week.  apologies for the delays.

**Comment by scollier** [comment]
@praiskup this got me further.  Thanks.  Now I have an auth issue when I try to login.  I see that you removed the "trust" line from the old Dockerfile.  How are you authenticating?

Docker logs:

```
<snip>
creating system views ... ok
loading system objects' descriptions ... ok
creating collations ... ok
creating conversions ... ok
creating dictionaries ... ok
setting privileges on built-in objects ... ok
creating information schema ... ok
loading PL/pgSQL server-side language ... ok
vacuuming database template1 ... ok
copying template1 to template0 ... ok
copying template1 to postgres ... ok
syncing data to disk ... ok

WARNING: enabling "trust" authentication for local connections
You can change this by editing pg_hba.conf or using the option -A, or
--auth-local and --auth-host, the next time you run initdb.

Success. You can now start the database server using:

    postgres -D /var/lib/pgsql/data
or
    pg_ctl -D /var/lib/pgsql/data -l logfile start

LOG:  redirecting log output to logging collector process
HINT:  Future log output will appear in directory "pg_log".
```

Login attempt:

```
# psql -h 172.17.0.7 -U postgres
Password for user postgres: 
psql: FATAL:  password authentication failed for user "postgres"
```

Database is running:

```
# docker exec 5b821f5b1a50 ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
postgres     1  0.0  0.1 337004 18940 ?        Ss+  18:00   0:00 postgres -D /var/lib/pgsql/data
postgres    89  0.0  0.0 190584  3272 ?        Ss   18:00   0:00 postgres: logger process   
postgres    91  0.0  0.0 337004  3940 ?        Ss   18:00   0:00 postgres: checkpointer process  
postgres    92  0.0  0.0 337004  5508 ?        Ss   18:00   0:00 postgres: writer process   
postgres    93  0.0  0.0 337004  3940 ?        Ss   18:00   0:00 postgres: wal writer process   
postgres    94  0.0  0.0 337708  6792 ?        Ss   18:00   0:00 postgres: autovacuum launcher process  
postgres    95  0.0  0.0 192680  4312 ?        Ss   18:00   0:00 postgres: stats collector process  
postgres   111  0.0  0.0  35888  2876 ?        Rs   18:06   0:00 ps aux
```

Image version:

```
# docker exec 5b821f5b1a50 cat /etc/redhat-release
Fedora release 21 (Twenty One)
```

**Comment by praiskup** [comment]
Truth.  Sorry I missed that docs inconsistency.

The 'trust' is probably not good secure option, and I was asked to not
generate default passwords..  I was asked to not require defined admin
password either (by environment variable e.g.) because that may not be
needed in all cases.  So the answer is in 'container-usage' output.

I'm not sure that we should make the 'README.md' as complicated as
container-usage output is, so let me propose another patch.  If you'll dislike
that patch, I can of course mirror 'container-usage' and README.md'.

**Comment by scollier** [comment]
OK.  I read through the container-usage auth section.  I think the reference to that from the README is fine.  This section does not work for me:

```
    $ id
    uid=26(postgres) gid=26(postgres) groups=26(postgres)
    $ psql
    psql (9.2.10)
    Type "help" for help
    postgres=#
```
 As I do not have a postgres user on the host.  Nor do I want to create one.  So, I tried the environment variable method:

```
docker run -v /root/pgsqlsocket:/var/run/postgresql -v "`pwd`/data:/var/lib/pgsql/data" -e POSTGRESQL_ADMIN_PASSWORD=test123 -dt -p 5432:5432 username/postgresql
```

Then a login:

```
# psql -h 172.17.0.14 -U postgres
Password for user postgres:
```

Which failed.

The env var was set, according to "docker inspect"

```
# docker inspect --format '{{ .Config.Env }}' dc3
[POSTGRESQL_ADMIN_PASSWORD=test123 PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin container=docker]
```

I change into the container to test and still doesn't work.

```
# docker exec -it dc30 bash
bash-4.3$ psql -h 172.17.0.14 -U postgres
Password for user postgres: 
psql: FATAL:  password authentication failed for user "postgres"
```

Thoughts?  Thanks for helping here.

**Comment by praiskup** [comment]
Possibly, we could give the user quick help how to change the password
for 'postgres' user?
```
docker exec -ti 3c54dbe54023 psql
psql (9.4.1)
Type "help" for help.

postgres=# \password 
Enter new password: 
Enter it again: 
postgres=#
```

Let me check what could be wrong with your use case...

**Comment by scollier** [comment]
@praiskup That did work for me.  I was able to change the password and then login to the container using psql.  I'm not sure why the env var wasn't setting the password.  I looked in:

Fedora-Dockerfiles/postgresql/root/usr/bin

And I did not see where it was setting that password.

**Comment by praiskup** [comment]
Scott, did you reuse the (already) initialized data volume?  That would mean
POSTGRESQL_ADMIN_PASSWORD variable is not used - as you have already
set 'trust' for your 'postgres' user.  You need to remove `data/*` files in this
case to enforce new initialization.  Probably good idea to throw a warning?

**Comment by praiskup** [comment]
Sorry, not 'trust' of course.  Its too late here in CEST :) probably.  Substitute the previous
sentences into: You could have already generated  'postgres' user without default password...

**Comment by praiskup** [comment]
Sorry, not 'trust' of course.  Its too late here in CEST :) probably.  Substitute the previous
sentences into: You could have already generated  'postgres' user without default password...

**Comment by scollier** [comment]
@praiskup ah, yes.  i did use an intialized volume.  tested again and it's working now.  Where does it get set though?

**Comment by scollier** [comment]
@praiskup ah, yes.  i did use an intialized volume.  tested again and it's working now.  Where does it get set though?

**Comment by praiskup** [comment]
You can use '-e CONT_DEBUG=3' if that helps, not sure now.  However the responsible code
is in root/usr/libexec/cont-postgresql-initdb .

**Comment by scollier** [comment]
Thanks @praiskup LGTM.

**Comment by praiskup** [comment]
Scott, thanks a lot for the review & merge!

**Pull request merged**
