### PR TITLE
Dockerfile for ZNC

### PR DESCRIPTION
**Pull request by praveenkumar**
This will be used to create znc container based on fedora base image.

### CODE REVIEW

**Comment by trishnaguha** [comment]
Ability to run the container with `atomic run` command would be nice.

**Comment by praveenkumar** [comment]
@trishnaguha I added `RUN` label to make it work with atomic cli, please give it a try.

**Comment by trishnaguha** [comment]
@praveenkumar Thanks! :+1: from me.

**Comment by trishnaguha** [comment]
@scollier @baude Could you please review this PR? :)

**Comment by scollier** [comment]
LGTM.  Thanks @praveenkumar

**Pull request merged**
