### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by jayesef**
remove duplicated yum install in line 8
replace yum by dnf for fedora 22
replace java 1.7 by java 1.8 for fedora 22
These changes were necessary to make it work properly on my fedora 22

### CODE REVIEW

**Comment by scollier** [comment]
Hi @jkomn We are still ironing out the details.  But what @LalatenduMohanty suggested was that we create branches for each version of Fedora here.  21, 22, etc... Now, that means that this PR would need to be applied to all three branches, with the exception of the dnf commit, which would only be applied to the later versions of Fedora.  Let me think about this for a bit and figure out best way to proceed.

**Comment by LalatenduMohanty** [comment]
@scollier yes, we need a simple policy with respect to this. For example every patch should go to master first (unless it is not applicable for master) then we we should back port the patch if required.

**Comment by jkomn** [comment]
I see, in any case you have already done great work on this, thanks!
If I run into further issues I'll keep on contributing my solutions, but I'm quite new with Docker and hadoop.

**Comment by scollier** [comment]
LGTM .  Thanks for the updates.

**Pull request merged**
