### PR TITLE
cadvisor: New Dockerfile

### PR DESCRIPTION
**Pull request by cgwalters**
This will allow us to move it out of the tree.

### CODE REVIEW

**Comment by scollier** [comment]
Reviewing right now.  I am seeing the same results as you did regarding display of container utilization.  In my tests, it lists all the containers, but the graphs are not updated.

I tried the google provided cadvisor and it worked.  My first inclination is to take a look at the versions running.   The one from google is tagged 0.10.1, the package from Fedora is:  0.6.2-0.1.git89088df which maps to this release from google: https://github.com/google/cadvisor/commit/89088df70eca64cf9d6b9a23a3d2bc21a30916d6

So, we are several versions behind, in the 0.7.0 release from google, I see this commit message:

"All stats in the UI are now updated.".

Maybe that's the issue, we are just to behind to have a functioning cadvisor on Fedora?

**Comment by ingvagabund** [comment]
Eric wrote me kubernetes has decided to embed cadvisor into the kubelet. And he believes
we plan to actually drop cadvisor from all atomic trees. I can update cadvisor to the latest 0.10.1. Do we still need it?

**Comment by scollier** [comment]
Hey @ingvagabund, do we know when cadvisor will be embedded into the kubelet?  If it's going to be pretty soon, I'd say, drop this.  If not, can we build a package and test it out here?

**Comment by ingvagabund** [comment]
@scollier, cadvisor-0.10.1 is built for f21,f22 and f23. You can test it.
Eric will now more about embedding date.

**Comment by scollier** [comment]
@ingvagabund Thanks.  I tested by enabling updates-testing.  Graphs showed up.  Couldn't see the containers anymore though.. So we'll keep this around until it's cadvisor is merged into k8s.

/cc @cgwalters

**Pull request merged**
