### PR TITLE
add fedmsg tools image

### PR DESCRIPTION
**Pull request by goern**

### CODE REVIEW

**Comment by bkabrda** [comment]
Thanks for the PR.
I think I only have one slight issue with this - you put the files under `fedmsg` directory, but I'd expect this directory to have a Dockerfile for the actual fedmsg *server*. IMO it'd make sense to put this into directory called "fedmsg-tail", because that describes precisely what your image is. At one point, I believe we'll have an image containing the actual fedmsg server and I think it should occupy `fedmsg` directory.

**Comment by scollier** [comment]
@goern any thoughts on @bkabrda's comment?

**Comment by goern** [comment]
@bkabrda @scollier ping

**Comment by scollier** [comment]
LGTM.

**Pull request merged**
